name: C++ Build

on:
  push:
    branches: [ cmake ]
  pull_request:
    branches: [ cmake ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B build
    
    - name: Build
      run: cmake --build build
    
    - name: List built files
      run: ls -la build
      if: runner.os != 'Windows'
    
    - name: List built files (Windows)
      run: dir build
      if: runner.os == 'Windows'
